# Generated by Django 4.2.7 on 2023-11-29 16:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, choices=[('1', 'Mr'), ('2', 'Mrs'), ('3', 'Miss'), ('4', 'Ms'), ('5', 'Dr'), ('6', 'Prof')], default='1', max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('personal_website', models.URLField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='ZAStreetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(blank=True, choices=[('1', 'Personal'), ('2', 'Business')], default='1', max_length=2, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('apartment_name', models.CharField(blank=True, max_length=200, null=True)),
                ('apartment_number', models.IntegerField(blank=True, null=True)),
                ('suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lead')),
            ],
            options={
                'verbose_name': 'South African Street Address',
                'verbose_name_plural': 'South African Street Addresses',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(blank=True, choices=[('1', 'LinkedIn'), ('2', 'Facebook'), ('3', 'Instagram'), ('4', 'Twitter'), ('5', 'Other')], default='1', max_length=2, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lead')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='social_media_links',
            field=models.ManyToManyField(to='dashboard.socialmedialink'),
        ),
    ]
