# Generated by Django 4.2.7 on 2023-11-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lead_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='month',
            new_name='title',
        ),
    ]
