# Generated by Django 4.2.7 on 2023-11-29 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_work_address_lead_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(blank=True, choices=[('1', 'Phone Call'), ('2', 'Email'), ('3', 'Instant Message')], default='1', max_length=2, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lead')),
            ],
        ),
    ]
