# Generated by Django 4.2.7 on 2023-11-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='communications',
            field=models.ManyToManyField(to='dashboard.communication'),
        ),
    ]
