# Generated by Django 4.2.7 on 2023-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_lead_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='facebook_profile_link',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
