# Generated by Django 4.2.7 on 2023-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_lead_facebook_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='facebook_profile_link',
        ),
    ]
