# Generated by Django 4.2.7 on 2023-11-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_lead_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lead'),
        ),
    ]
