# Generated by Django 4.2.7 on 2023-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_socialmedialink_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='social_media',
            field=models.CharField(choices=[('1', 'Facebook'), ('2', 'Instagram'), ('3', 'Other')], default='1', max_length=2),
        ),
    ]
