# Generated by Django 4.2.7 on 2023-11-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_socialmedialink_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='social_media',
            field=models.CharField(choices=[('1', 'LinkedIn'), ('2', 'Facebook'), ('3', 'Instagram'), ('4', 'Twitter'), ('5', 'Other')], default='1', max_length=2),
        ),
    ]
