# Generated by Django 4.2.7 on 2023-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_socialmedialink_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedialink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
