# Generated by Django 4.2.7 on 2023-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_socialmedialink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, choices=[('1', 'Mr'), ('2', 'Mrs'), ('3', 'Miss'), ('4', 'Ms'), ('5', 'Dr'), ('6', 'Prof')], default='1', max_length=2),
        ),
    ]
