# Generated by Django 4.2.7 on 2023-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_lead_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, choices=[('1', 'Mr'), ('2', 'Mrs'), ('3', 'Miss'), ('4', 'Ms'), ('5', 'Dr'), ('6', 'Prof')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='social_media',
            field=models.CharField(blank=True, choices=[('1', 'LinkedIn'), ('2', 'Facebook'), ('3', 'Instagram'), ('4', 'Twitter'), ('5', 'Other')], default='1', max_length=2, null=True),
        ),
    ]
