# Generated by Django 4.2.7 on 2023-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_lead_title_alter_socialmedialink_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='work_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
