# Generated by Django 4.2.7 on 2023-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_lead_company_name_lead_job_title_lead_work_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
