# Generated by Django 4.2.7 on 2023-11-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_lead_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
