# Generated by Django 4.2.7 on 2023-11-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_lead_personal_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetAddressZA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
