# Generated by Django 4.2.7 on 2023-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_streetaddressza_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streetaddressza',
            options={'verbose_name': 'South African Street Address', 'verbose_name_plural': 'South African Street Addresses'},
        ),
        migrations.AddField(
            model_name='streetaddressza',
            name='apartment_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='streetaddressza',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
