# Generated by Django 4.2.7 on 2023-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_streetaddressza_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='work_address',
        ),
        migrations.AddField(
            model_name='lead',
            name='work_address',
            field=models.ManyToManyField(to='dashboard.streetaddressza'),
        ),
    ]
