# Generated by Django 4.2.7 on 2023-11-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_lead_work_address_lead_work_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetaddressza',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.lead'),
        ),
    ]
