# Generated by Django 4.2.7 on 2023-11-29 15:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_streetaddressza_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
